### ISSUE TITLE
Render MermaidJS diagrams

### ISSUE THREAD

**Issue by DaveJarvis** [css4j/echosvg#35]
**Background**

MermaidJS is a popular (38k ⭐) server-side rendering suite for translating text-based diagram descriptions into scalable vector graphics. No open source rendering library that I tried can render its diagrams (see [issue](https://github.com/mermaid-js/mermaid/issues/2485)). Kroki is a REST-based service for rendering text-based diagrams, including mermaid, as SVG.

**Replicate**

1. Copy attached [`mermaid.svg.txt`](https://github.com/css4j/echosvg/files/7560618/mermaid.svg.txt) as `samples/mermaid.svg` (see [Kroki render](https://kroki.io/mermaid/svg/eNpNzr0OgjAcBPCdp7hRB-QNNHz4Masb6VBK0zZg_6S2GhTf3cJgnH93l1OODxrXKgHyGrkdyUowpOl2KrmFlv2ACcUKR4InKON1aDaCbtkYXsFLobPOUWewjgvF3EP5xomec1qQ9c40MbbDJ3q5eFXjLAdy3liFJqg72M_2NS6au1lMK_k_HeK99kGCLz2WfAHnUzg5)).
1. Add the following method to `SamplesRenderingTest.java`:
    ``` java
	@Test
	public void testMermaid() throws TranscoderException, IOException {
		test("samples/mermaid.svg");
	}
    ```
1. Run the unit test method.

**Expected**

Diagram is rendered.

**Actual**

Exception while validating the XML: the `<div>` element is unexpected.

**Work around**

Comment out XML validation in `SAXDocumentFactory.java`:
``` java
  //parser.setFeature("http://xml.org/sax/features/validation", isValidating);
  //parser.setProperty("http://xml.org/sax/properties/lexical-handler", this);
```

**Continue**

1. Re-run the test.

**Expected**

The diagram renders.

**Actual**

`<style>` is expected to be `<style type="text/css">`.

**Work around**

Add the missing `type` attribute. Consider relaxing the DTD.

**Continue**

1. Re-run the test.

**Expected**

Diagram is rendered.

**Actual**

Cannot parse the CSS.

**Work around**

None. At this point the CSS parser cannot handle the semi-colon. Specifically, in `CSSParser.java`, the `handleSemicolon` method fires an `endOfPropertyDeclaration`. Is parsing the double-quotes for `"trebuchet ms"` causing the parser to get into an invalid state?

**Addendum**

Using the [W3C validator service](https://validator.w3.org/#validate_by_upload+with_options), the document validates correctly as an SVG 1.1 document.

**Comment by carlosame** [comment]
Thank you for your bug report, Dave.

> Add the following method to SamplesRenderingTest.java:
```java
@Test
public void testMermaid() throws TranscoderException, IOException {
	test("samples/mermaid.svg");
}
```
You want to use `testNV("samples/mermaid.svg")` which is a non-validating test, so you do not need to comment anything out nor add any attribute. Once I run that test, I directly get this:
```css
The following stylesheet represents an invalid 
CSS document.
#mermaid-1637216322989 {font-family:"trebuchet ms",verdana,arial,sans-serif;font-size:16px;fill:#333;}#mermaid-1637216322989 .error-icon{fill:#552222;}#mermaid-1637216322989 .error-text{fill:#552222;stroke:#552222;}#mermaid-1637216322989 .edge-thickness-normal{stroke-width:2px;}#mermaid-1637216322989 .edge-thickness-thick{stroke-width:3.5px;}#mermaid-1637216322989 .edge-pattern-solid{stroke-dasharray:0;}#mermaid-1637216322989 .edge-pattern-dashed{stroke-dasharray:3;}#mermaid-1637216322989 .edge-pattern-dotted{stroke-dasharray:2;}#mermaid-1637216322989 .marker{fill:#333333;stroke:#333333;}#mermaid-1637216322989 .marker.cross{stroke:#333333;}#mermaid-1637216322989 svg{font-family:"trebuchet ms",verdana,arial,sans-serif;font-size:16px;}#mermaid-1637216322989 .label{font-family:"trebuchet ms",verdana,arial,sans-serif;color:#333;}#mermaid-1637216322989 .cluster-label text{fill:#333;}#mermaid-1637216322989 .cluster-label span{color:#333;}#mermaid-1637216322989 .label text,#mermaid-1637216322989 span{fill:#333;color:#333;}#mermaid-1637216322989 .node rect,#mermaid-1637216322989 .node circle,#mermaid-1637216322989 .node ellipse,#mermaid-1637216322989 .node polygon,#mermaid-1637216322989 .node path{fill:#ECECFF;stroke:#9370DB;stroke-width:1px;}#mermaid-1637216322989 .node .label{text-align:center;}#mermaid-1637216322989 .node.clickable{cursor:pointer;}#mermaid-1637216322989 .arrowheadPath{fill:#333333;}#mermaid-1637216322989 .edgePath .path{stroke:#333333;stroke-width:2.0px;}#mermaid-1637216322989 .flowchart-link{stroke:#333333;fill:none;}#mermaid-1637216322989 .edgeLabel{background-color:#e8e8e8;text-align:center;}#mermaid-1637216322989 .edgeLabel rect{opacity:0.5;background-color:#e8e8e8;fill:#e8e8e8;}#mermaid-1637216322989 .cluster rect{fill:#ffffde;stroke:#aaaa33;stroke-width:1px;}#mermaid-1637216322989 .cluster text{fill:#333;}#mermaid-1637216322989 .cluster span{color:#333;}#mermaid-1637216322989 div.mermaidTooltip{position:absolute;text-align:center;max-width:200px;padding:2px;font-family:"trebuchet ms",verdana,arial,sans-serif;font-size:12px;background:hsl(80, 100%, 96.2745098039%);border:1px solid #aaaa33;border-radius:2px;pointer-events:none;z-index:100;}#mermaid-1637216322989 :root{--mermaid-font-family:"trebuchet ms",verdana,arial,sans-serif;}
Original message:
you try to use an empty method in Adapter-class
```
which is caused by the custom property `--mermaid-font-family`.

Neither EchoSVG nor Batik support [custom properties](https://www.w3.org/TR/css-variables-1/) (which implies supporting `var()`). So this issue could be reformulated as "please support custom properties".

My long-term intention is to land an alternative SVGOM implementation in EchoSVG, based on CSS4J's native DOM. Native DOM fully supports `var()`, `calc()`, etc. (in fact it even supports `calc` computations that are spec-compliant but that browsers do not support yet).

To write that thing I was waiting for [Houdini's TypedOM](https://www.w3.org/TR/css-typed-om-1/) to be implemented by a browser so I could use a supported standard CSSOM API (the CSS Object Model that EchoSVG/Batik implement is deprecated and no browser supports it). However, I may still write a SVGOM implementation inheriting from native DOM, one that does not implement any CSSOM yet; that thing would allow people to render SVG that includes advanced CSS like `var()` and `calc()`. No promises at all though.
